### ISSUE TITLE
Creative Commons Attribution-NonCommercial 4.0, really ?

### ISSUE THREAD

**Issue by quatreplusquatre** [GravitAG/gravit#231] opened 2014-12-22 17:28 UTC
Hi Gravit gang,

When I saw Gravit, I was really excited. Finally, an open source design software, which has potential. By cons when I look at your license, I said: What? What's the point of putting open source? What is our interest to contribute?

So you do not want the Gravit is used in a business context? Or you have not applied the correct license maybe?

For I read on your website ... or open up new Ways of collaborating with customers!

Can you help me? Because I intended to use my strong free software business.

Thanks

**Comment by webmaven** [comment] 2015-01-02 23:08
Source code under CC-BY-NC is essentially 'look but don't touch'. There is very little that may be learned from code that cannot be modified even in the most trivial ways.

Furthermore, CC licenses in general are not really suitable for software. I would strongly suggest that you re-examine your choice of license and choose an open source software license that will meet your business *and* community needs. GPLv3 seems like it would be a good choice here since, while it does not prevent commercial use of the source, it does prevent another party from creating proprietary improvements that cannot then be used by you as well, and also still does not allow them to use your trademarks without permission.

**Comment by hsoft** [comment] 2015-01-05 19:21
At work, we were also very excited about this product and were already talking about getting involved until I said "wait, is that a non-commercial clause there?". It's a show stopper for us.

The incentive for a business to contribute in an open source fashion is to not have its hands tied like we have in closed source (which is why we talk about "free software"). I understand your reasons for choosing this license, but as others have said earlier, you should also be aware of the doors this choice closes.

**Comment by pieplu** [comment] 2015-01-07 16:27
We have built a professional design app, offer it for free to everyone and opened our source to have others learn from it?
    

I'm also a designer, and if I would like use Gravit for a client (make a small website for a skate shop), I can't! Because with a CC-NC we can't use gravit to build commercial products.
Why use Gravit in this case?
And, why contribute to Gravit? If at the end you can only use it to design Christmas card for your Family...

With CC-NC Gravit become a Sketch over the landscape.

**Comment by anderswelt** [comment] 2015-01-08 07:23
To @everyone here -- I think there's a BIG miss-understanding:
The code is CC-NC that is, you can contribute and also use the code for free open source products but not commercially.

HOWEVER: Everything created with the Gravit Application can be OF COURSE used in any way you want be it commercial or not or whatever... We're "just" talking from the code base here

**Comment by anderswelt** [comment] 2015-01-08 07:29
@quatreplusquatre The commercial licenses depend on your planned usage of the code as we're trying to provide the best pricing for everyone. If you need more information, drop as an email at info@gravit.io

**Comment by hsoft** [comment] 2015-01-08 13:05
The license is not properly worded for software, so it's unclear, by the license, what rights are being given. Despite what the Gravit team says, the lack of licensing clarity is a risk for a business. After all, [CC themselves discourage the use of their licenses for software](https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).

**Comment by quasado** [comment] 2015-01-09 04:19
Interesting, we're not happy with it either. Any suggestion (except gpl) for a free license that only includes commercial usage of *the app* itself to protect our investements yet gives contributors any other freedom they wish?

**Comment by quatreplusquatre** [comment] 2015-01-09 15:35
it depends what you want to do. To see more clearly,
https://tldrlegal.com/

**Comment by webmaven** [comment] 2015-01-09 22:04
@quasado, what sorts of commercial use are you trying to prevent?

**Comment by joufella** [comment] 2015-01-12 17:35
@anderswelt wrote:
> HOWEVER: Everything created with the Gravit Application can be OF COURSE used in any way you want be it commercial or not or whatever... We're "just" talking from the code base here.

You fail to understand the license covers not only the redistribution terms but also the usage of the software in its executable form. Using Gravit means creating documents. No commercial use means you cannot create documents for commercial purpose.

**Comment by pieplu** [comment] 2015-01-12 23:50
@quasado An other problem:
If I contribute to gravit under CC-NC, I keep the copyright (like any other contribution),
and quasado can't use my contribute code for commercial use...

> Any suggestion (except gpl) for a free license that only includes commercial usage of the app itself to protect our investements

Maybe an licence for web-app, Affero-GPL: http://www.gnu.org/licenses/agpl-3.0.en.html

Exemple of free software web app who works:
https://www.odoo.com/ (AGPL)
https://about.gitlab.com/
https://gitorious.org/ (AGPL)
http://www.shinken-monitoring.org/ (AGPL)
http://fr.wikipedia.org/wiki/POV-Ray (AGPL)
http://owncloud.org/ (AGPL)

**Comment by anderswelt** [comment] 2015-01-13 08:30
The issue with GPL and AGPL is that we want to prevent someone from re-using our code in a commercial product that's about it, for that we're selling a commercial license with which we're funding the development. I cannot find a license that allows as much freedom as GPL/AGPL but prevents that one single point.. any ideas?

**Comment by hsoft** [comment] 2015-01-13 13:48
You seem to be in a logical impossibility. You cannot restrict the usage of a software and still call it "open source" or "free software".

I'm unaware of your particular business model, but one possible road for you might be dual licensing. You license your software as GPL, which is "coercitive freedom" and prevent what is usually seen in the proprietary world as "commercial usage" and at the same time, you use your own privately copyrighted copy of the software for whatever purpose. Even if you license your work as GPL, if you're still the sole author, you retain full copyright wereas other people are bound by the terms of the GPL.

It complicates your contribution model a bit because if you want to use external contributions in your own "private" copy, you'll have to ask contributors to grant you the right to do so (give you full copyright). If you don't, you'll be bound by the terms of the GPL for those contributions (and thus, the contributions will only be applicable to the GPL fork of your work).

But then again, I'm compelled to insist: "free software" and "commercial usage" have always been totally compatible. So, even with GPL, someone could always use it for "commercial" purposes. Their only restriction will be that they'll have to distribute the source code, licensed under the GPL to whomever they distribute their software. But that doesn't exclude any kind of money exchange in the process.

**Comment by webmaven** [comment] 2015-01-20 18:48
@anderswelt:
> The issue with GPL and AGPL is that we want to prevent someone from re-using our code in a commercial product 

Be more specific, please. In what way does the GPL or AGPL not accomplish your goals? What exact scenario are you trying to prevent?

If someone were to take some of Gravit's code and incorporate it into a commercial product, they would likely be obligated to release their product's code as well. This is usually considered a sufficient deterrent to proprietary software vendors staying away from code licensed under reciprocal licenses such as the GPL or AGPL.

**Comment by anderswelt** [comment] 2015-01-24 09:35
@webmaven The problem is with JS-Code. Specifically spoken, you could encrypt/minify your JS-Code and release it. This would suffice the GPL/AGPL but no one could do anything with that code.

**Comment by alid** [comment] 2015-01-27 14:11
>The problem is with JS-Code. Specifically spoken, you could encrypt/minify your JS-Code and release it. This would suffice the GPL/AGPL but no one could do anything with that code.

No, this will *not* meet the requirements of GPL/AGPL. They would have to provide the corresponding source code of their changed version. The source code should be human readable, so a minified/encrypted JS file is proprietary non-free software.

To learn more: https://www.gnu.org/philosophy/javascript-trap.html

**Comment by raphaelbastide** [comment] 2015-02-02 11:18
Until this issue is closed, you may want to changer or remove the mention “open source” on [this page](https://medium.com/design-with-gravit/gravit-will-become-open-source-4608f37aef2d), because up to now, this is untrue and as you can see users really think Gravit is [open source](https://www.youtube.com/watch?v=rHF6jVdcG2c).

**Comment by postcasio** [comment] 2015-02-03 15:57
The OSI is not the grand arbiter of what is and is not "open source". CC BY-NC licensed works are open source: you can view the source, you can modify the source, you can redistribute the source. The only thing you cannot do is profit from the source.

**Comment by anderswelt** [comment] 2015-03-05 15:55
as @postcasio pointed out, we're actually thinking that it full-fills the requirements of "open-source" thus closing this issue for now.

**Closed by anderswelt** 2015-03-05 15:55 UTC
Labels: question

**Comment by hsoft** [comment] 2015-03-05 16:07
With all respects, the point of this issue is not "can we legitimately use the term 'open source' to qualify our license", but rather answer to the above question:

> What's the point of putting open source? What is our interest to contribute?

IMHO, those questions haven't been answered yet.

**Comment by pieplu** [comment] 2015-03-06 04:42
I'm sorry, but I don't understand why this issue has been closed.
With CC NC, we can't use the product to make commercial images,
> cannot do is profit from the source

 and no interest to contribute, for us and for you! 
It's why CC licences are not for source code!

**Comment by postcasio** [comment] 2015-03-06 09:23
The real question is, what do the developers gain from contributing to your profit margin? You are not automatically entitled to make money off other people's work.

**Comment by hsoft** [comment] 2015-03-06 12:44
@postcasio on that, you are right. We aren't entitled to anything. We're just pointing that whatever the reason were for making Gravit CC-NC, it has likely missed its goals, whatever they were. You might as well have kept it closed source. For practical purposes, it's the same thing.

By closing this issue, you appear to sweep this problem under the rug, but that won't change the fact that you've probably missed your goals.

**Comment by hsoft** [comment] 2015-03-16 18:31
Sorry to revive this thread, but there is a very major logical implication that was missed here:

*Unless you make every external contributor sign a copyright waiver, you are also bound by the CC-NC as soon as you integrate these contributions*. This means that you possibly (I'm not a lawyer, this is an opinion based on what I've read around) *can't* use your own product commercially.

For example, the commit at https://github.com/NewSpaces/gravit/commit/328c6d974c02845b24a660d771232c86466d1020 , was it done by someone who gave you their copyright? Then you are possibly infringing @camelCaseD's copyright right now.

This is really not an issue that should be swept under the rug, because the more contributors you have, the more difficult this problem will be to untangle. It would be a shame to let a fine product sink in some murky legal waters.

**Comment by camelCaseD** [comment] 2015-03-18 19:04
Based off what @hsoft said see the following from [google](https://github.com/google/gxui/blob/master/README.md#contributing) for an idea of how this could be implemented.
